# Generated by Django 4.2.16 on 2024-11-17 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrival_time',
            new_name='departure',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='name',
            field=models.CharField(default='Unnamed Flight', max_length=100),
        ),
    ]
