# Generated by Django 4.2.16 on 2024-11-19 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_rename_departure_flight_departure_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destination',
            new_name='arrival_city',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('On Time', 'On Time'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
    ]
