# Generated by Django 4.2.16 on 2024-11-20 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0005_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='passengers',
        ),
        migrations.AddField(
            model_name='cart',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
