# Generated by Django 4.2.16 on 2024-11-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0009_remove_cart_added_at_alter_flight_departure_city_and_more'),
        ('airline', '0010_auto_20241130_1933'),
    ]

    operations = [
    ]
